# Generated by Django 3.2.7 on 2021-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Успешно выполнен'), ('failure', 'Завершен с ошибкой')], default='success', max_length=100, verbose_name='Статус запроса')),
                ('text', models.TextField(verbose_name='Результат запроса')),
            ],
        ),
    ]
